GreatLand/GreatLand/Controllers/ConfirmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GreatLand.Models;

namespace GreatLand.Controllers
{
    public class ConfirmController : Controller
    {

        private Dal dal = new Dal();
        private BusinessLogic.BusinessLogic logic = new BusinessLogic.BusinessLogic();

        // GET: Confirm
        public ActionResult Index(long id)
        {
            var cust = new CustTaskModelBson();
            dal.ConfirmReservation(id);
            cust.Confirmation = id;
            return View(cust);
        }
    }
}

GreatLand/GreatLand/Controllers/CoushattaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GreatLand.Models;
using GreatLand.BusinessLogic;
using System.Threading;
using System.Threading.Tasks;


using MongoDB.Driver;
using MongoDB.Bson;
using MongoDB.Bson.Serialization;
namespace GreatLand.Controllers
{
   
    public class CoushattaController : Controller
    {

        private Dal dal = new Dal();
        private BusinessLogic.BusinessLogic logic = new BusinessLogic.BusinessLogic();


        // GET: Coushatta
        public ActionResult Index(int? id)
        {

            List<SelectListItem> travelDate = new List<SelectListItem>();
            var days = logic.Get7Days();



            foreach (var i in days)
            {
                travelDate.Add(new SelectListItem { Text = i.Value, Value = i.Key.ToString() });
            }

            travelDate.Add(new SelectListItem { Text = "", Value = "", Selected = true });
            ViewData["TravelDate"] = travelDate;

            //2-Go get list of bus route departures for today (1) is always today

            //var d = (from i in days select i.Key).First();

            //logic.GetBusRouteDepartureToday(d, 1);   day and 1 is casino number = tb_casino
            //var routes = logic.GetBusRouteDepartureToday(d, Convert.ToInt16(Miscellaneous.CasinoDBNumber.Lauberge));

            //List<SelectListItem> li = new List<SelectListItem>();
            //foreach(var l in routes)
            //{
            //    li.Add(new SelectListItem { Text = l.Value, Value = l.Key.ToString() });
            //}

            ViewData["Location"] = "";

            //3-Go get the route for the current pickup location
            //var greatLandRoute = new List<Routes>();
            //var loc = (from o in routes select o.Key).First();
            //var locDetail = logic.GetBusRouteDepartureDetails(Convert.ToInt32(loc), Convert.ToInt16(Miscellaneous.CasinoDBNumber.Lauberge));

            //foreach (var doc in LookupData.Laub_SouthHouston)
            //foreach (var doc in locDetail)
            //{

            //    //put an increment here to add the description 1 time
            //    int descCount = 0;

            //    greatLandRoute.Add(new Routes(doc.Route,
            //                                    doc.Day,
            //                                    doc.Depart,
            //                                    doc.ArriveCasino,
            //                                    doc.DepartCasino,
            //                                    doc.ReturnTime,
            //                                    doc.YouPay,
            //                                    doc.YouReceive,
            //                                    doc.DescriptionH,
            //                                    doc.DescriptionD,
            //                                    doc.SelectedParameter,
            //                                    doc.ManagerRouteNumber,
            //                                    doc.Route + "|" + d  // on the initial load - it will always load the today
            //                                    //doc.Id //ROUTE PLACE HOLDER
            //                                    )); 

            //    if (descCount == 0)
            //    {
            //        TempData["LocationDesc"] = doc.DescriptionH + ": " + doc.DescriptionD;
            //    }

            //    descCount++;
            //}

            TempData["LocationDesc"] = "";
            return View();
        }



        [HttpPost]
        public ActionResult Index()
        {
            //repopulate the travelDate
            var travelDateValue = Request["TravelDateValue"].ToString();
            List<SelectListItem> travelDate = new List<SelectListItem>();
            List<SelectListItem> li = new List<SelectListItem>();

            var days = logic.Get7Days();
            //1-The dropdowndate will retain the selected
            foreach (var i in days)
            {
                if (i.Key.ToString() == travelDateValue)
                {
                    travelDate.Add(new SelectListItem { Text = i.Value, Value = i.Key.ToString(), Selected = true });
                }
                else
                {
                    travelDate.Add(new SelectListItem { Text = i.Value, Value = i.Key.ToString() });
                }
            }
            ViewData["TravelDate"] = travelDate;
            var routes = logic.GetBusRouteDepartureToday(Convert.ToInt16(travelDateValue), Convert.ToInt16(Miscellaneous.CasinoDBNumber.Coushatta));

            //there is a route so we process
            if (routes.Count() > 0)
            {
                string searchValue = "";
                if (Request["SearchValue"] != null)
                {
                    //Go get list of bus route departures for the current travel date
                    //logic.GetBusRouteDepartureToday(d, 1);   day and 1 is casino number = tb_casino

                    searchValue = Request["SearchValue"].ToString();
                }



                //The dropdown will retain the selected
                foreach (var l in routes)
                {
                    if (l.Key.ToString() == searchValue)
                    {
                        li.Add(new SelectListItem { Text = l.Value, Value = l.Key.ToString(), Selected = true });
                    }
                    else
                    {
                        li.Add(new SelectListItem { Text = l.Value, Value = l.Key.ToString() });
                    }

                }

                ViewData["Location"] = li;

                //This is the 1st pass so we chose the default search value
                if (searchValue == "" && li != null)
                {
                    searchValue = li[0].Value;
                }


                //check to make sure the search value is in the new departure list since the date might have changed.
                var search = li.Find(item => item.Value.Equals(searchValue));

                List<Routes> location = new List<Routes>();
                if (search != null)
                {
                    location = dal.GetPickupLocationDB2(searchValue, travelDateValue, Convert.ToInt16(Miscellaneous.CasinoDBNumber.Coushatta));
                }
                else
                {
                    //null because the original search value has nothing from the new list            
                    var loc = (from o in routes select o.Key).First();
                    location = dal.GetPickupLocationDB2(loc, travelDateValue, Convert.ToInt16(Miscellaneous.CasinoDBNumber.Coushatta));

                    //logic.GetBusRouteDepartureDetails(Convert.ToInt32(loc)).ToList();
                }



                TempData["LocationDesc"] = (from values in location select values.DescriptionH + ": " + values.DescriptionD).First();

                return View(location);
            }


            List<Routes> locationdefault = new List<Routes>();
            return View(locationdefault);
        }

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult Confirm(CustTaskModelBson cust)
        {


            //Get the route for the heading

            //parse the id field
            string[] strArray = cust.Route.Split('|');
            //route
            var r = strArray[0];

            //day
            var d = strArray[1];

            var dayofWeek = logic.CalculateDayofWeekByNumber(Convert.ToInt16(d));


            var custTaskModelBson = new CustTaskModelBson();
            var greatLandRoute = new List<Routes>();

            var route = dal.GetLaubergePickupLocationDB(r);

            //var test = (from values in route where values.Route == id select values);

            foreach (var doc in route)
            {

                //var greatLa = BsonSerializer.Deserialize<CustTaskModel>(doc);
                greatLandRoute.Add(new Routes(doc.Route,
                                                dayofWeek.ToShortDateString(), //doc.Day,
                                                doc.Depart,
                                                doc.ArriveCasino,
                                                doc.DepartCasino,
                                                doc.ReturnTime,
                                                doc.YouPay,
                                                doc.YouReceive,
                                                doc.DescriptionH,
                                                doc.DescriptionD,
                                                1,
                                                 1, //ROUTE PLACE HOLDER
                                                ""
                                                ));

                TempData["Courses"] = doc.DescriptionH + ": " + doc.DescriptionD;




            }

            ViewData["route"] = greatLandRoute;

            var confirm = new CustTaskModel(cust.Route,
                                            cust.LastName,
                                            cust.FirstName,
                                            cust.Email,
                                            cust.Phone,
                                            cust.SeatsNumber,
                                            cust.Date,
                                            cust.CreatedDate,
                                            cust.UpDate,
                                            cust.PersonUpdate,
                                            cust.Notes,
                                            cust.Confirmation,
                                              cust.Traveler1Name,
                                            cust.Traveler2Name,
                                            cust.Traveler3Name,
                                            cust.Traveler4Name,

GreatLand/GreatLand/Views/Coushatta/Confirm.cshtml
@model GreatLand.Models.CustTaskModel

@{
    ViewBag.Title = "Review";
    Layout = "~/Views/Coushatta/_Layout.cshtml";

}

<h2>Reservation Review</h2>
@using (Html.BeginForm("Sub", "Coushatta"))
{
    @Html.ValidationSummary(true)

    <center>
        <div>
            <table>
                <tr><td> <div style="font-family:Verdana; font-size:small; font-weight:bold; text-align:left">LOCATION DETAILS </div> </td></tr>
                <tr><td><div style="font-family:Verdana; font-size:medium; text-align:left">@TempData["Courses"]</div></td></tr>
            </table>
            <table cellpadding="25" height="0">
                @foreach (var item in ViewData["route"] as List<GreatLand.Models.Routes>)
                {
                    <tr>
                        <th style="background-color:darkcyan; font-family:Verdana; font-size:medium; width:10%">
                            Route
                        </th>
                        <th style="background-color:darkcyan; font-family:Verdana; font-size:medium; width:15%">
                            Travel Date
                        </th>
                        <th style="background-color:darkcyan; font-family:Verdana; font-size:medium; width:15%">
                            Depart
                        </th>
                        <th style="background-color:darkcyan; font-family:Verdana; font-size:medium; width:15%">
                            Arrive Casino
                        </th>
                        <th style="background-color:darkcyan; font-family:Verdana;font-size:medium; width:15%">
                            Depart Casino
                        </th>
                        <th style="background-color:darkcyan; font-family:Verdana;font-size:medium; width:15%">
                            Return Time
                        </th>
                    </tr>
                        <tr>
                            <td style="font-family:Verdana;font-size:medium; width:10%">
                                @item.Route
                            </td>
                            <td style="font-family:Verdana;font-size:medium; width:15%">
                                @item.Day
                            </td>
                            <td style="font-family:Verdana;font-size:medium; width:15%">
                                @item.Depart
                            </td>
                            <td style="font-family:Verdana;font-size:medium; width:15%">
                                @item.ArriveCasino
                            </td>
                            <td style="font-family:Verdana;font-size:medium; width:15%">
                                @item.DepartCasino
                            </td>
                            <td style="font-family:Verdana;font-size:medium; width:15%">
                                @item.ReturnTime
                            </td>
                        </tr>
                }
            </table>
        </div>
    </center>

    <center>
              <div>
                <br />
                <br />

                <table border="0">

                    <tr>
                        <td><div class="editor-label" style="text-align:left"><a href=@Url.Content("/Home/Policy") target="_blank">Travel Disclosure</a></div></td>


                        <td>
                            <div class="editor-field">
                                @{
                                    var TRitems = new SelectList(new[]
                                    {
                                            new SelectListItem {Text = "1", Value = "Please read the Travel Disclosure" },
                                            new SelectListItem {Text = "2", Value = "I have read the Travel Disclosure" },
                                        }, "Text", "Value");
                                }
                                @Html.DropDownListFor(model => model.TravelDisclosure, @TRitems, new { @onchange = "ShowHideDiv(this.value)" })
                                @Html.ValidationMessageFor(model => model.TravelDisclosure)
                            </div>

                        </td>
                    </tr>

                    <tr>
                        <td style="visibility:hidden">
                            <div class="editor-label" style="text-align:right">
                                Route
                            </div>
                        </td>
                        <td style="visibility:hidden">
                            <div class="editor-field">
                             
                                @Html.EditorFor(model => model.Route)
                                @Html.ValidationMessageFor(model => model.Route)
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <div class="editor-label" style="text-align:left">
                                <strong>First Name</strong>
                            </div>
                        </td>
                        <td style="width:400px">
                            <div class="editor-field">
                                @Html.DisplayFor(model => model.FirstName)
                            </div>                  
                    
                        </td>
                    </tr>


                    <tr>
                        <td>
                            <div class="editor-label" style="text-align:left">
                                <strong>Last Name</strong>
</div>
                        </td>
                        <td style="width:400px">
                            <div class="editor-field">
                                @Html.DisplayFor(model => model.LastName)
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <div class="editor-label" style="text-align:left">
                                <strong>Email</strong>
</div>
                        </td>
                        <td style="width:400px">
                            <div class="editor-field">
                                @Html.DisplayFor(model => model.Email)
                            </div>
                    </tr>

                    <tr>
                        <td>
                            <div class="editor-label" style="text-align:left">
                                <strong>Phone</strong>
                            </div>
                        </td>
                        <td>
                            <div class="editor-field">
                                @Html.DisplayFor(model => model.Phone)         
                            </div>
                    </tr>
                    <tr>
                        <td>
                            <div class="editor-label" style="text-align:left">
                                <strong>Comments</strong>
                            </div>
                        </td>
                        <td>
                            <div class="editor-field">
                                @Html.DisplayFor(model => model.Notes)     
                            </div>
                    </tr>

                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td><div class="editor-label" style="text-align:left"><Strong># of Passengers </Strong></div></td>
                        <td>
                            <div class="editor-field">
                                @Html.DisplayFor(model => model.SeatsNumber)                               
                            </div>

                        </td>

                    </tr>
                    <tr>
                        <td>
                            <div class="editor-label" style="text-align:left">
                                <strong>Passenger 1</strong>
                            </div>
                        </td>
                        <td>
                            <div id="dvPassport" class="editor-field">
                                @Html.DisplayFor(model => model.Traveler1Name)   
                            </div>
                    </tr>
                    <tr>
                        <td>
                            <div class="editor-label" style="text-align:left">
                                <strong>Passenger 2</strong>
                            </div>
                        </td>
                        <td>
                            <div class="editor-field">
                                @Html.DisplayFor(model => model.Traveler2Name)                                
                            </div>
                    </tr>
                    <tr>
                        <td>
                            <div class="editor-label" style="text-align:left">
                                <strong>Passenger 3</strong>
                            </div>
                        </td>
                        <td>
                            <div class="editor-field">
                                @Html.DisplayFor(model => model.Traveler3Name)                        
                            </div>
                    </tr>
                    <tr>
                        <td>
                            <div class="editor-label" style="text-align:left">
                                <strong>Passenger 4</strong>
                            </div>
                        </td>
                        <td>
                            <div class="editor-field">
                                @Html.DisplayFor(model => model.Traveler4Name)                                
                            </div>
                    </tr>
                    <tr>
                        <td>
                            <div class="editor-label" style="text-align:left">
                                <strong>Passenger 5</strong>
                            </div>
                        </td>
                        <td>
                            <div class="editor-field">
                                @Html.DisplayFor(model => model.Traveler5Name)                                
                            </div>
                    </tr>
                    <tr>
                        <td>
                            <div class="editor-label" style="text-align:left">
                                <strong>Passenger 6</strong>
                            </div>
                        </td>
                        <td>
                            <div class="editor-field">
                                @Html.DisplayFor(model => model.Traveler6Name)                                
                            </div>
                    </tr>


                </table>

            </div>
            <div style="align-items:center">
                <!--<input type="submit" value="Create" />-->
                click Submit to continue
                <br />
                <input type="submit" value="Submit" name="action" />
            </div>

    </center>

    @*
        <div class="editor-field">
            @Html.EditorFor(model => model.UpDate)
            @Html.ValidationMessageFor(model => model.UpDate)
        </div>

        <div class="editor-field">
            @Html.EditorFor(model => model.CreatedDate)
            @Html.ValidationMessageFor(model => model.CreatedDate)
        </div>
    *@
                                    <div style="visibility:hidden">
                                        @Html.TextBoxFor(model => model.Date)
                                        @Html.EditorFor(model => model.FirstName)   
                                        @Html.EditorFor(model => model.LastName)
                                        @Html.EditorFor(model => model.Email)
                                        @Html.EditorFor(model => model.Phone)
                                        @Html.TextAreaFor(model => model.Notes)
                                        @{
                                            var items = new SelectList(new[]
                                            {
                                            new SelectListItem {Text = "1", Value = "1" },
                                            new SelectListItem {Text = "2", Value = "2" },
                                             new SelectListItem {Text = "3", Value = "3" },
                                            new SelectListItem {Text = "4", Value = "4" },
                                             new SelectListItem {Text = "5", Value = "5" },
                                            new SelectListItem {Text = "6", Value = "6" },
                                        }, "Text", "Value");
                                        }
                                        @Html.DropDownListFor(model => model.SeatsNumber, @items, new { @onchange = "ShowHideDiv(this.value)" })

                                        @Html.EditorFor(model => model.Traveler1Name)
                                        @Html.EditorFor(model => model.Traveler2Name)
                                        @Html.EditorFor(model => model.Traveler3Name)
                                        @Html.EditorFor(model => model.Traveler4Name)
                                        @Html.EditorFor(model => model.Traveler5Name)
                                        @Html.EditorFor(model => model.Traveler6Name)
                            

                             
                                    </div>


                                    }
<p>
    @*Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

GreatLand/GreatLand/Views/Coushatta/Index.cshtml
@model  List<GreatLand.Models.Routes>
@using GridMvc.Html
@{
    ViewBag.Title = "Coushatta";
}

<h2>Coushatta Casino Resort</h2>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Coushatta</title>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>



</head>
<body>

    @using (Html.BeginForm("Index", "Coushatta"))
    {
        <center>Reservations may only be made 7 days in advance due to possible schedule changes.</center>
        <br />

        if (Model != null)
        {
                <table>
                    <tr><td> <div style="font-family:Verdana; font-size:small; font-weight:bold; text-align:left">LOCATION DETAILS </div> </td></tr>
                    <tr><td><div style="font-family:Verdana; font-size:medium; text-align:left">@TempData["LocationDesc"]</div></td></tr>
                </table>
                <br />
                <br />

    
     
                <table>
                    <tr><td><div style="font-family:Verdana; font-size:small; font-weight:bold; text-align:left">Please Choose Travel Date &nbsp;</div></td>
                        <td>
                            <div class="editor-label" style="text-align:center">
                                @Html.DropDownList("TravelDateValue", ViewData["TravelDate"] as List<SelectListItem>, new { @onchange = "this.form.submit();" })
                            </div>
                        </td>
                    </tr>
                    @if (ViewData["Location"] != null)
                    {
                    <tr><td><div style="font-family:Verdana; font-size:small; font-weight:bold; text-align:left">Please Choose Departure Location &nbsp;</div></td><td><Div>@Html.DropDownList("SearchValue", ViewData["Location"] as List<SelectListItem>, new { @onchange = "this.form.submit();" })</Div></td></tr>
                    }
                 </table>

     

                <div>
                    @Html.Partial("PartialView1", Model)

                </div>
        }
        else
        {

            <table>
                <tr>
                    <td><div style="font-family:Verdana; font-size:small; font-weight:bold; text-align:left">Please Choose Travel Date &nbsp;</div></td>
                    <td>
                        <div class="editor-label" style="text-align:center">
                            @Html.DropDownList("TravelDateValue", ViewData["TravelDate"] as List<SelectListItem>, new { @onchange = "this.form.submit();" })
                        </div>
                    </td>
                </tr>

            
            </table>
        }
    }
</body>
    </html>

GreatLand/GreatLand/Views/Coushatta/PartialView1.cshtml
@model  List<GreatLand.Models.Routes>
@using GridMvc.Html

@*<table>
    <tr><td> <div style="font-family:Verdana; font-size:small; font-weight:bold; text-align:left">3) Choose Departure time: </div> </td></tr>
</table>*@
<br />
<div id="bakHolidays" style="width:100%">
    @Html.Grid(Model).Columns(columns =>
   {
       //columns.Add(c => c.Route).Titled("Route");
       //columns.Add(c => c.Day).Titled("Day").Filterable(false);
       columns.Add(c => c.Depart).Titled("Depart");
       columns.Add(c => c.ArriveCasino).Titled("Arrive Casino");
       columns.Add(c => c.DepartCasino).Titled("Depart Casino");
       columns.Add(c => c.ReturnTime).Titled("Return Time");
       //columns.Add(c => c.YouPay).Titled("You Pay");
       //columns.Add(c => c.YouReceive).Titled("You Receive");
       columns.Add(model => model.Route).Titled("RESERVE").Filterable(true).Sanitized(false).Encoded(false).RenderValueAs(model => Html.ActionLink("Reservation", "Create", "Coushatta", new { id = model.ReservRedirectParam }, null).ToHtmlString());


   }).WithPaging(15).Sortable(false)
</div>
<br />
<div>Policies</div>
<div style="font-size:smaller;font-family:Verdana">
    Seating arrangements are at check-in on a first come, first serve basis.
    One person per ticket and is per one seating arrangement ONLY.
    All tickets are non-refundable, non-exchangeable, and non-transferable once the bus departs.
    All passengers must be 21 years or older with a valid Federal Picture I.D. No copy accepted.
    Please see Reservation & Travel Policies for complete travel disclosure.
</div>

GreatLand/GreatLand/Views/Coushatta/PartialView2.cshtml
@model  GreatLand.Models.PartialViewModel
@using GridMvc.Html
@{

    <div>
        <h2>@Model.PartialView2Message</h2>
    </div>
}

GreatLand/GreatLand/Views/Coushatta/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - GreatLand</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquerymin")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryuimin")

    @Scripts.Render("~/bundles/SeatNumber")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/cssjqueryui")
    @Styles.Render("~/Content/jqueryui")
    @Scripts.Render("~/bundles/modernizr")



</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Home", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Casino Trips <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("L'Auberge", "Index", "Lauberge")</li>
                            <li>@Html.ActionLink("Coushatta", "Index", "Coushatta")</li>
                            <li>@Html.ActionLink("Delta Downs", "Index", "DeltaDowns")</li>
                            <li>@Html.ActionLink("Golden Nugget", "Index", "GoldenNugget")</li>
                            <li>@Html.ActionLink("Isle of Capri", "Index", "IsleofCapri")</li>
                        </ul>
                    </li>
                    @*<li>@Html.ActionLink("Charters", "Charters", "Home")</li>*@
                    <li>@Html.ActionLink("Reservation & Travel Policies", "Policy", "Home")</li>
                    @*<li>@Html.ActionLink("Office", "Login", "Account")</li>*@
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - GreatLand Tours</p>
        </footer>
    </div>


</body>
@RenderSection("scripts", required: false)
</html>