GreatLand/GreatLand/Controllers/ConfirmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GreatLand.Models;

namespace GreatLand.Controllers
{
    public class ConfirmController : Controller
    {

        private Dal dal = new Dal();
        private BusinessLogic.BusinessLogic logic = new BusinessLogic.BusinessLogic();

        // GET: Confirm
        public ActionResult Index(long id)
        {
            var cust = new CustTaskModelBson();
            dal.ConfirmReservation(id);
            cust.Confirmation = id;
            return View(cust);
        }
    }
}

GreatLand/GreatLand/Controllers/OfficeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using GreatLand.Models;
using GreatLand;
using System.Configuration;

using System.Threading;
using System.Threading.Tasks;

using MongoDB.Driver;
using MongoDB.Bson;
using MongoDB.Bson.Serialization;
using Microsoft.AspNet.Identity;


using GreatLand.BusinessLogic;
namespace GreatLand.Controllers
{





    //[AdminSuperAdmin]
    //[CustomAttribute]
    [Authorize]
    public class OfficeController : BaseController
    {
        private Dal dal = new Dal();
        private bool disposed = false;
        private BusinessLogic.BusinessLogic logic = new BusinessLogic.BusinessLogic();
        string email = "";

        [Authorize]
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            //if (Session["UserID"] == "" || Session["UserID"] == null)
            //{
            //    var user = Session["UserID"];
            //    //we can'f find the user session. send him to relogin
            //    Response.Redirect("~/Account/Login");

            //}
            var id = HttpContext.GetOwinContext();
            var claim = id.Authentication.User.Claims;
            foreach(var i in claim)
            {
                email = i.Value;
            }
            if (email ==  null || email == "")
            {
                //we can find his credential send hime to login
                RedirectToAction("LogIn", "Account", new { area = "" });
            }
            base.OnActionExecuting(filterContext);
        }


        [HttpPost]
        public ActionResult GoldenNuggetEdit(CustTaskModelBson cust)
        {
            var routes = logic.GetBusRouteOffice(Convert.ToInt16(Miscellaneous.CasinoDBNumber.GoldenNugget));
            List<SelectListItem> li = new List<SelectListItem>();

            //in case they submit before choosing a location
            if (cust.Country == "0")
            {
                foreach (var l in routes)
                {
                    li.Add(new SelectListItem { Text = l.Value, Value = l.Key.ToString() });
                }

                li.Add(new SelectListItem { Text = "Please select Location", Value = "0", Selected = true });
            }
            else
            {
                //The dropdown will retain the selected
                foreach (var l in routes)
                {
                    if (cust.Country == l.Value)
                    {
                        li.Add(new SelectListItem { Text = l.Value, Value = l.Key.ToString(), Selected = true });
                    }
                    else
                    {
                        li.Add(new SelectListItem { Text = l.Value, Value = l.Key.ToString() });
                    }
                }
            }


            ViewData["Country"] = li;


            ViewData["PickupTime"] = null;

            //get all of the route for at pickup - and selected = true on the route

            List<SelectListItem> states = new List<SelectListItem>();
            var loc = new List<Routes>();
            loc = dal.GetPickupLocationDB(Convert.ToInt16(cust.Country), Convert.ToInt16(Miscellaneous.CasinoDBNumber.GoldenNugget));
            //TempData["LocationDesc"] = (from values in location select values.DescriptionH + ": " + values.DescriptionD).First();

            //in case they submit before choosing a location
            if (cust.Country == "0")
            {
                states.Add(new SelectListItem { Text = "Select schedule", Value = "0", Selected = true });
            }
            else
            {

                foreach (var i in loc)
                {
                    if (i.Route == cust.State)
                    {
                        states.Add(new SelectListItem { Text = "Route: " + i.Route + " - Day: " + i.Day + " -  Depart: " + i.Depart + " -  ArriveCasino: " + i.ArriveCasino + " -  DepartCasino: " + i.DepartCasino + " -  ReturnTime: " + i.ReturnTime, Value = i.Route, Selected = true });
                    }
                    else
                    {
                        states.Add(new SelectListItem { Text = "Route: " + i.Route + " - Day: " + i.Day + " -  Depart: " + i.Depart + " -  ArriveCasino: " + i.ArriveCasino + " -  DepartCasino: " + i.DepartCasino + " -  ReturnTime: " + i.ReturnTime, Value = i.Route });
                    }
                }
            }



            ViewData["PickupTime"] = states;

            if (logic.IsValidDate(cust.Date))
            {
                var tr = Request["State"].ToString();
                cust.Route = tr;
   

                if (email != null)
                {
                    cust.PersonUpdate = email;
                }
                else
                {
                    cust.PersonUpdate = "NA";
                }

                dal.EditTask(cust);


                ViewData["route"] = cust;
                return RedirectToAction("Confirm", cust);
            }
            else
            {
                //return false and post it to the user
                return View();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeltaDownEdit(CustTaskModelBson cust)
        {
            var routes = logic.GetBusRouteOffice(Convert.ToInt16(Miscellaneous.CasinoDBNumber.DeltaDown));
            List<SelectListItem> li = new List<SelectListItem>();

            //in case they submit before choosing a location
            if (cust.Country == "0")
            {
                foreach (var l in routes)
                {
                    li.Add(new SelectListItem { Text = l.Value, Value = l.Key.ToString() });
                }

                li.Add(new SelectListItem { Text = "Please select Location", Value = "0", Selected = true });
            }
            else
            {
                //The dropdown will retain the selected
                foreach (var l in routes)
                {
                    if (cust.Country == l.Value)
                    {
                        li.Add(new SelectListItem { Text = l.Value, Value = l.Key.ToString(), Selected = true });
                    }
                    else
                    {
                        li.Add(new SelectListItem { Text = l.Value, Value = l.Key.ToString() });
                    }
                }
            }


            ViewData["Country"] = li;


            ViewData["PickupTime"] = null;

            //get all of the route for at pickup - and selected = true on the route

            List<SelectListItem> states = new List<SelectListItem>();
            var loc = new List<Routes>();
            loc = dal.GetPickupLocationDB(Convert.ToInt16(cust.Country), Convert.ToInt16(Miscellaneous.CasinoDBNumber.DeltaDown));
            //TempData["LocationDesc"] = (from values in location select values.DescriptionH + ": " + values.DescriptionD).First();

            //in case they submit before choosing a location
            if (cust.Country == "0")
            {
                states.Add(new SelectListItem { Text = "Select schedule", Value = "0", Selected = true });
            }
            else
            {

                foreach (var i in loc)
                {
                    if (i.Route == cust.State)
                    {
                        states.Add(new SelectListItem { Text = "Route: " + i.Route + " - Day: " + i.Day + " -  Depart: " + i.Depart + " -  ArriveCasino: " + i.ArriveCasino + " -  DepartCasino: " + i.DepartCasino + " -  ReturnTime: " + i.ReturnTime, Value = i.Route, Selected = true });
                    }
                    else
                    {
                        states.Add(new SelectListItem { Text = "Route: " + i.Route + " - Day: " + i.Day + " -  Depart: " + i.Depart + " -  ArriveCasino: " + i.ArriveCasino + " -  DepartCasino: " + i.DepartCasino + " -  ReturnTime: " + i.ReturnTime, Value = i.Route });
                    }
                }
            }



            ViewData["PickupTime"] = states;

            if (logic.IsValidDate(cust.Date))
            {
                var tr = Request["State"].ToString();
                cust.Route = tr;
        

                if (email != null)
                {
                    cust.PersonUpdate = email;
                }
                else
                {
                    cust.PersonUpdate = "NA";
                }


                dal.EditTask(cust);


                ViewData["route"] = cust;
                return RedirectToAction("Confirm", cust);
            }
            else
            {
                //return false and post it to the user
                return View();
            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        public ActionResult CoushattaEdit(CustTaskModelBson cust)
        {
            var routes = logic.GetBusRouteOffice(Convert.ToInt16(Miscellaneous.CasinoDBNumber.Coushatta));
            List<SelectListItem> li = new List<SelectListItem>();

            //in case they submit before choosing a location
            if (cust.Country == "0")
            {
                foreach (var l in routes)
                {
                    li.Add(new SelectListItem { Text = l.Value, Value = l.Key.ToString() });
                }

                li.Add(new SelectListItem { Text = "Please select Location", Value = "0", Selected = true });
            }
            else
            {
                //The dropdown will retain the selected
                foreach (var l in routes)
                {
                    if (cust.Country == l.Value)
                    {
                        li.Add(new SelectListItem { Text = l.Value, Value = l.Key.ToString(), Selected = true });
                    }
                    else
                    {

GreatLand/GreatLand/Views/Office/Confirm.cshtml
@model GreatLand.Models.CustTaskModelBson

@{
    ViewBag.Title = "Confirmed";
    Layout = "~/Views/Office/_Layout.cshtml";

}

<h2>Reservation Confirmed</h2>
<div>
  
    <div>Give the Customer this confirmation number <strong> @Html.DisplayFor(model => model.Confirmation)</strong> bring it at boarding time. Contact 713-777-9988 | info@greatlandtours.com for any questions</div>
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Confirmation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Confirmation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Route)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Route)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.SeatsNumber)
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.SeatsNumber)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Traveler1Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Traveler1Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Traveler2Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Traveler2Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Traveler3Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Traveler3Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Traveler4Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Traveler4Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Traveler5Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Traveler5Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Traveler6Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Traveler6Name)
        </dd>
    </dl>
</div>
<p>
    @*Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

GreatLand/GreatLand/Views/Office/CoushattaIndex.cshtml
@model  List<GreatLand.Models.Routes>
@using GridMvc.Html
@{
    ViewBag.Title = "Coushatta";
}

<h2>Coushatta Casino Office Report</h2>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Office</title>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>

</head>
<body>

    @using (Html.BeginForm("CoushattaIndex", "Office"))
    {



        @Html.DropDownList("SearchValue", ViewData["Location"] as List<SelectListItem>, new { @onchange = "this.form.submit();" })

        <div>
            @Html.Partial("CoushattaPartialView1", Model)

        </div>


        <div>
            @*Html.Partial("PartialView2", new GreatLand.Models.PartialViewModel { PartialView2Message = Model.PartialView2Message })*@
        </div>


    }
</body>
</html>

GreatLand/GreatLand/Views/Office/CoushattaPartialView1.cshtml
@model  List<GreatLand.Models.Routes>
@using GridMvc.Html

<br />
<br />
<br />
<table>
    <tr><td> <div style="font-family:Verdana; font-size:small; font-weight:bold; text-align:left">PICKUP LOCATION DETAILS </div> </td></tr>
    <tr><td><div style="font-family:Verdana; font-size:medium; text-align:left">@TempData["LocationDesc"]</div></td></tr>
</table>
<div id="bakHolidays" style="width:100%">
    @Html.Grid(Model).Columns(columns =>
   {
       //columns.Add(c => c.Route).Titled("Route");
       columns.Add(c => c.Day).Titled("Day").Filterable(false);
       columns.Add(c => c.Depart).Titled("Depart");
       columns.Add(c => c.ArriveCasino).Titled("Arrive Casino");
       columns.Add(c => c.DepartCasino).Titled("Depart Casino");
       columns.Add(c => c.ReturnTime).Titled("Return Time");
       //columns.Add(c => c.YouPay).Titled("You Pay");
       //columns.Add(c => c.YouReceive).Titled("You Receive");
       columns.Add(model => model.Route).Titled("REPORT").Filterable(true).Sanitized(false).Encoded(false).RenderValueAs(model => Html.ActionLink("See Report", "CoushattaReport", "Office", new { id = model.Route }, null).ToHtmlString());


   }).WithPaging(15).Sortable(false)
</div>
@*<br />
<br />
<br />
<div>Policies</div>
<div style="font-size:smaller;font-family:Verdana">

    RESERVATION HOURS: 8:30AM - 10:00PM, MONDAY TO SUNDAY
    Weekend trips schedule may be 30 minutes late due to road construction, traffic and weather.

    Reservations must be made a day before for DAY TRIPS and by 5:00PM for NIGHT TRIPS.
    Office reservations will be automatic cancelled 15 minutes prior to departure time.
    Seating arrangements are at check-in on a first come, first serve basis.
    One person per ticket and is per one seating arrangement ONLY.
    All tickets are non-refundable, non-exchangeable, and non-transferable once the bus departs.
    All passengers must be 21 years or older with a valid Federal Picture I.D. No copy accepted.
    No luggage permitted, unless arranged with office in advance with your casino hotel reservation.
    We assume no liability for damage to the bag, nor for loss or damage to the contents of the bag.

    Additional Fee may apply without casino card of destination. We reserve the right to alter or cancel without notice.
    THE BUS COMPANY AND THE CASINOS ARE NOT RESPONSIBLE FOR GUESTS WHO MISS THEIR SCHEDULED DEPARTURE. PASSENGERS ARE RESPONSIBLE FOR RIDING THE CORRECT BUS FOR THEIR INTENDED DESTINATION AND EXITING THE BUS AT THE CORRECT STOP.
    TRANSPORTATION SERVICES ARE PROVIDED FOR GAMING CUSTOMERS ONLY. THIS BUS SERVICE IS NOT FOR GENERAL PUBLIC TRANSPORTATION.
</div>*@

GreatLand/GreatLand/Views/Office/DeltaDownsReport.cshtml
@model IEnumerable<GreatLand.Models.CustReportModel>
@using GridMvc.Html
@{
    ViewBag.Title = "DeltaDownsReport";
}

<h2>Delta Downs Report</h2>


<html>
<head>
    <title>Office</title>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/themes/Gridmvc.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />


    <script src="@Url.Content("~/Scripts/jquery-2.1.4.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-2.1.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.11.4.min.js")"></script>

    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>




</head>
<body>

    <div id="bakHolidays" style="width:100%">
        @Html.Grid(Model).Columns(columns =>
   {
       columns.Add(c => c.Route).Titled("Route").Filterable(false);
       columns.Add(c => c.LastName).Titled("Last Name").Filterable(true);
       columns.Add(c => c.FirstName).Titled("First Name").Filterable(true);
       columns.Add(c => c.Email).Titled("Email");
       columns.Add(c => c.Phone).Titled("Phone");
       columns.Add(c => c.SeatsNumber).Titled("# of Seats");
       columns.Add(c => c.Date).Titled("Travel Date");
       columns.Add(c => c.Notes).Titled("Notes");
       columns.Add(c => c.CreatedDate).Titled("Date Created");
       columns.Add(c => c.UpDate).Titled("Date Updated");
       columns.Add(c => c.PersonUpdate).Titled("Person Updated");
       columns.Add(c => c.Id).Titled("Edit").Filterable(true).Sanitized(false).Encoded(false).RenderValueAs(model => Html.ActionLink("Edit", "LaubergeEdit", "Office", new { id = model.Id }, null).ToHtmlString());
       columns.Add(c => c.DeleteId).Titled("Delete").Filterable(true).Sanitized(false).Encoded(false).RenderValueAs(model => Html.ActionLink("Delete", "LaubergeReport", "Office", new { id = model.Id }, null).ToHtmlString());

   }).WithPaging(15).Sortable(true)
    </div>
    
</body>
</html>

GreatLand/GreatLand/Views/Office/GoldenNuggetIndex.cshtml
@model  List<GreatLand.Models.Routes>
@using GridMvc.Html
@{
    ViewBag.Title = "Golden Nugget";
}

<h2>Golden Nugget Casino Office Report</h2>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Office</title>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>

</head>
<body>

    @using (Html.BeginForm("GoldenNuggetIndex", "Office"))
    {



        @Html.DropDownList("SearchValue", ViewData["Location"] as List<SelectListItem>, new { @onchange = "this.form.submit();" })

        <div>
            @Html.Partial("GoldenNuggetPartialView1", Model)

        </div>


        <div>
            @*Html.Partial("PartialView2", new GreatLand.Models.PartialViewModel { PartialView2Message = Model.PartialView2Message })*@
        </div>


    }
</body>
</html>

GreatLand/GreatLand/Views/Office/ManagerPageBlock.cshtml
@model List<GreatLand.Models.ManagerView>
@{
    ViewBag.Title = "Manager Route Block";
    Layout = "_Layout.cshtml";
}

<h2>Manager Route Block</h2>



@*<div>Route 2</div>
<table>
    <tr>
        <td width="100">
            @Html.CheckBox("Pickupbeechnut")
        </td>
        <td width="100">
            @Html.CheckBox("Pickupguessner")
        </td>
    </tr>
</table>*@

@using (Html.BeginForm("ManagerBlock", "Office"))
{
    //@Html.DropDownList("SearchValue", ViewData["Location"] as List<SelectListItem>, new { @onchange = "this.form.submit();" })
    foreach(var items in Model)
    {
        <table>
            <tr>
                <td>
                    Enable Block:
                </td>
                <td>
                    @Html.RadioButton("Status", "Enable", true)
                    
                </td>
              
            </tr>
            <tr>
                <td>
                    Disable Block:
                </td>
                <td>
                    @Html.RadioButton("Status", "Disable", false)
                </td>
            </tr>
            <tr>
                <td>
                    Block Start Date/Time:
                </td>
                <td>
                    @Html.TextBox("StartBlock", @items.StartVoidDate)
                </td>
            </tr>
            <tr>
                <td>
                    Block End Date/Time:
                </td>
                <td>
                    @Html.TextBox("EndBlock", @items.EndVoidDate)
                </td>
            </tr>
            <tr>
                <td>@Html.TextBox("RouteId", @items.RouteNumber, new { style = "display:none;" })</td>
            </tr>
            

        </table>
     
    }

    <div style="align-items:center">
        <!--<input type="submit" value="Create" />-->

        <input type="submit" value="Submit" name="action" />
    </div>


    <div>
        @Html.Partial("PartialViewManagerRouteBlock", Model)

    </div>
}

GreatLand/GreatLand/Views/Office/PartialViewManagerRoute.cshtml
@model List<GreatLand.Models.ManagerView>
@using GridMvc.Html

<br />
<br />
<br />
@*<table>
    <tr><td> <div style="font-family:Verdana; font-size:small; font-weight:bold; text-align:left">PICKUP LOCATION DETAILS </div> </td></tr>
    <tr><td><div style="font-family:Verdana; font-size:medium; text-align:left">@TempData["LocationDesc"]</div></td></tr>
</table>*@
<div id="ManagerRoute" style="width:100%">
    @Html.Grid(Model).Columns(columns =>
   {
       //columns.Add(c => c.Route).Titled("Route");
       //columns.Add(c => c.Id).Titled("ID").Filterable(false);
       columns.Add(c => c.RouteNumber).Titled("RouteNumber");
       columns.Add(c => c.Casino).Titled("Casino");
       columns.Add(c => c.Route).Titled("Route");
       columns.Add(c => c.DepartTime).Titled("Depart Time");
       columns.Add(c => c.DayOfTheWeek).Titled("Day of the Week");
       columns.Add(c => c.PickUpLocations).Titled("Pickup");       
       columns.Add(c => c.Active).Titled("Active");
       columns.Add(c => c.StartVoidDate).Titled("Begin Stop Pickup Date");
       columns.Add(c => c.EndVoidDate).Titled("End Stop Pickup Date");
       columns.Add(model => model.Id).Titled("Block Route").Filterable(true).Sanitized(false).Encoded(false).RenderValueAs(model => Html.ActionLink("Block", "ManagerPageBlock", "Office", new { id = model.Id }, null).ToHtmlString());


   }).WithPaging(15).Sortable(false)
</div>

GreatLand/GreatLand/Views/Office/PartialViewManagerRouteBlock.cshtml
@model List<GreatLand.Models.ManagerView>
@using GridMvc.Html

<br />
<br />
<br />
@*<table>
    <tr><td> <div style="font-family:Verdana; font-size:small; font-weight:bold; text-align:left">PICKUP LOCATION DETAILS </div> </td></tr>
    <tr><td><div style="font-family:Verdana; font-size:medium; text-align:left">@TempData["LocationDesc"]</div></td></tr>
</table>*@
<div id="ManagerRoute" style="width:100%">
    @Html.Grid(Model).Columns(columns =>
   {
       //columns.Add(c => c.Route).Titled("Route");
       //columns.Add(c => c.Id).Titled("ID").Filterable(false);
       columns.Add(c => c.RouteNumber).Titled("RouteNumber");
       columns.Add(c => c.Casino).Titled("Casino");
       columns.Add(c => c.Route).Titled("Route");
       columns.Add(c => c.DepartTime).Titled("Depart Time");
       columns.Add(c => c.DayOfTheWeek).Titled("Day of the Week");
       columns.Add(c => c.PickUpLocations).Titled("Pickup");       
       columns.Add(c => c.Active).Titled("Active");
       columns.Add(c => c.StartVoidDate).Titled("Begin Stop Pickup Date");
       columns.Add(c => c.EndVoidDate).Titled("End Stop Pickup Date");
       //columns.Add(model => model.Id).Titled("Block Route").Filterable(true).Sanitized(false).Encoded(false).RenderValueAs(model => Html.ActionLink("Block", "ManagerPageBlock", "Office", new { id = model.Id }, null).ToHtmlString());


   }).WithPaging(15).Sortable(false)
</div>

GreatLand/GreatLand/Views/Office/ReportMainParm.cshtml
@{
    ViewBag.Title = "Main Report";
    Layout = "~/Views/Office/_Layout.cshtml";
}

<h2>Main Report</h2>

@using (Html.BeginForm("ManagerBlock", "Office"))
{
   

        <table>
            @*<tr>
                <td>
                    Enable Block:
                </td>
                <td>
                    @Html.RadioButton("Status", "Enable", true)

                </td>

            </tr>*@
            <tr>
                <td>
                    Casino:
                </td>
                <td>
                    @Html.DropDownList("SearchValue", ViewData["Location"] as List<SelectListItem>)
                </td>
            </tr>
            <tr>
                <td>
                    From Date:
                </td>
                <td>
                    @Html.TextBox("Start")
                </td>
            </tr>
            <tr>
                <td>
                    To Date:
                </td>
                <td>
                    @Html.TextBox("End")
                </td>
            </tr>
            <tr>
                @*<td>@Html.TextBox("RouteId", @items.RouteNumber, new { style = "display:none;" })</td>*@
            </tr>


        </table>

    <div style="align-items:center">
        <!--<input type="submit" value="Create" />-->

        <input type="submit" value="Submit" name="action" />
    </div>


    <div>
        @*@Html.Partial("PartialViewManagerRouteBlock", Model)*@

    </div>
}